### ISSUE TITLE
Async control flow

### ISSUE THREAD

**Issue by JGAntunes** [iamanishroy/netlify-plugin-js-obfuscator#2]
There's a couple of places where we rely on `async/await` logic without a need to it, given these functions are either synchronous or rely on callbacks for control flow. Specifically:

### `fs.writeFile`
`fs.writeFile` is a [callback based mehod](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback) meaning [awaiting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) on it will not produce any effect. An alternative if we want to use async/await would be to use [`util.promisify`](https://nodejs.org/api/util.html#util_util_promisify_original)
https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/ca7d29c28849b0066756dc0e6f43c2dae1a3ca6b/index.js#L26

However if we want to rely on its callback interface then we need correctly handle its control flow as well as its error:
https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/main/index.js#L29

A possible solution using `async/await` and `util.promisify`:

```js
const fs = require("fs"); 
const util = require("util"); 
const readFile = util.promisify(fs.readFile)
const writeFile = util.promisify(fs.writeFile)

(...)

// Reading the files -> obfuscating the code -> Writing the obfuscated code
const obfuscateCode = async (filePath, custom) => {
  const file = await readFile(filePath, "utf8");
  const obfuscationResult = JavaScriptObfuscator.obfuscate(file, {
    compact: custom[0],
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
    numbersToExpressions: custom[1],
    simplify: custom[2],
    shuffleStringArray: custom[3],
    splitStrings: custom[4],
  });
  await writeFile(
    filePath,
    obfuscationResult.getObfuscatedCode(),
  );
};

```

**Note:** Since Node 10 there's also the ability to use the [`fs.promises`](https://nodejs.org/api/fs.html#fs_fs_promises_api) however, we still need to support Node 8.

### `JavaScriptObfuscator.obfuscate`
Reading through [its docs](https://github.com/javascript-obfuscator/javascript-obfuscator#usage) doesn't seem like the `javascript-obfuscator` is an asynchronous function. As such, `await` won't be necessary here:
https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/ca7d29c28849b0066756dc0e6f43c2dae1a3ca6b/index.js#L17

**Comment by iamanishroy** [comment]
Thanks for the fix 👍
