### ISSUE TITLE
`constants.FUNCTIONS_SRC` can be undefined

### ISSUE THREAD

**Issue by JGAntunes** [iamanishroy/netlify-plugin-js-obfuscator#3]
As per [our documentation](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#constants) the `FUNCTIONS_SRC` constant can be undefined:

https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/ca7d29c28849b0066756dc0e6f43c2dae1a3ca6b/index.js#L41

This would mean the following replacement:

https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/ca7d29c28849b0066756dc0e6f43c2dae1a3ca6b/index.js#L9

Could result in:
```js
directoryFilter: ["!node_modules", "!plugins", "!undefined"],
```

Depending on how the module reasons with the `directoryFilter`, and what sort of assets the user has, might not have that much impact... However might be worth considering some sort of check beforehand and only using the variable if it actually exists.

**Comment by iamanishroy** [comment]
Issue Fixed!
`const excludedDir = ["!node_modules", "!plugins"];

// listing all the '.js' files
const getJsFiles = async (directory, func_dir) => {
  if (func_dir) {
    excludedDir.push(`!${func_dir}`);
  }
  const files = await readdirp.promise(directory, {
    fileFilter: "*.js",
    directoryFilter: excludedDir,
  });
  return files.map((file) => file.fullPath);
};`

**Comment by iamanishroy** [comment]
issue fixed!
```
const excludedDir = ["!node_modules", "!plugins"];

// listing all the '.js' files
const getJsFiles = async (directory, func_dir) => {
  if (func_dir) {
    excludedDir.push(`!${func_dir}`);
  }
  const files = await readdirp.promise(directory, {
    fileFilter: "*.js",
    directoryFilter: excludedDir,
  });
  return files.map((file) => file.fullPath);
};
```

**Comment by iamanishroy** [comment]
issue fixed!

```
var excludedDir = ["!node_modules", "!plugins"];

// listing all the '.js' files
const getJsFiles = async (directory, func_dir) => {
  if (func_dir) {
    excludedDir.push(`!${func_dir}`);
  }
  const files = await readdirp.promise(directory, {
    fileFilter: "*.js",
    directoryFilter: excludedDir,
  });
  return files.map((file) => file.fullPath);
};
```
