### ISSUE TITLE
Top level error handling 

### ISSUE THREAD

**Issue by JGAntunes** [iamanishroy/netlify-plugin-js-obfuscator#4]
Currently the top level handler of the plugin relies on a high level `try/catch` to handle errors coming from the `obfuscateCode` function. This makes it hard for the internal build process to distinguish between user errors and bugs, given the top level catch will re-throw all the errors using `failBuild()` which is used to convey user errors.

https://github.com/iamanishroy/netlify-plugin-js-obfuscator/blob/ca7d29c28849b0066756dc0e6f43c2dae1a3ca6b/index.js#L43-L57

We would like to suggest removing this top level `try/catch` and instead keep these blocks as close as possible to the functions that may throw errors that we want to handle. Specifically for this case, your use of the `readdirp` package will make sure the files are in place, so any errors that come from file reading/writing would probably mean there's a problem with the build system (so no need to handle those). In the end we're left with validating the `JavaScriptObfuscator` package. Picking up on the suggestions from #2, for the `obfuscateCode` functions we could have:

```js
// Reading the files -> obfuscating the code -> Writing the obfuscated code
const obfuscateCode = async (filePath, custom) => {
 const file = await readFile(filePath, "utf8");
  
  try {
    const obfuscationResult = JavaScriptObfuscator.obfuscate(file, {
      compact: custom[0],
      controlFlowFlattening: true,
      controlFlowFlatteningThreshold: 1,
      numbersToExpressions: custom[1],
      simplify: custom[2],
      shuffleStringArray: custom[3],
      splitStrings: custom[4],
    });
  } catch (error) {
    return utils.build.failBuild("Failed to Obfuscate JS .", { error });
  }
  await writeFile(
    filePath,
    obfuscationResult.getObfuscatedCode(),
  );
};
```

**Edit:** Changed this suggestion based on some input from @ehmicky 🙏

**Comment by JGAntunes** [comment]
FYI I've ended up editing this suggestion ☝️

**Comment by iamanishroy** [comment]
Removed `try/catch` block from top level 
Thank for explaining issue 👍
