### ISSUE TITLE
Bundle size increases 9x

### ISSUE THREAD

**Issue by ankitgoyal100** [iamanishroy/netlify-plugin-js-obfuscator#5]
Hi, my bundle size increased 9x after I installed this plugin.

I'm using this plugin on a CRA (Create React App). Is there a way to only obfuscate my project's code and not the code of my `node_modules`?

**Comment by iamanishroy** [comment]
> Hi, my bundle size increased 9x after I installed this plugin.

This plugin is made for vanilla JavaScript only.

> Is there a way to only obfuscate my project's code and not the code of my `node_modules`?

Check [webpack-obfuscator](https://www.npmjs.com/package/webpack-obfuscator)
